DROP TABLE users;
DROP TYPE UserStatus;
DROP TABLE locations;
DROP TYPE LocationStatus;
DROP TABLE ratings;
DROP TYPE RatingStatus;
DROP TABLE visits;
DROP TABLE photos;
DROP TYPE PhotoStatus ;
DROP TABLE likes;
DROP TYPE LikeStatus;
